# Generated by Django 4.2 on 2023-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=20)),
                ('admin', models.BooleanField()),
                ('profilepic', models.CharField(max_length=9999)),
                ('creditcard', models.CharField(max_length=255)),
                ('StreetName', models.CharField(max_length=255)),
                ('HouseNumber', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('PostalCode', models.CharField(max_length=255)),
            ],
        ),
    ]
