# Generated by Django 4.2 on 2023-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_users_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
