# Generated by Django 4.2 on 2023-05-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ProfilePic',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
