# Generated by Django 4.2 on 2023-05-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCardholder', models.CharField(max_length=255)),
                ('CardNumber', models.CharField(max_length=255)),
                ('ExpirationDate', models.DateField()),
                ('CVC', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CIP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.creditcard'),
        ),
    ]
