# Generated by Django 4.2 on 2023-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_creditcard_cvc_alter_creditcard_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='CVC',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='CardNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
