# Generated by Django 4.2 on 2023-05-11 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_creditcard_cvc_alter_creditcard_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='CVC',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='CardNumber',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
