# Generated by Django 4.2 on 2023-05-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('admin', models.BooleanField()),
                ('profilepic', models.CharField(max_length=9999)),
                ('creditcard', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartOf2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.product')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.topping')),
            ],
        ),
        migrations.CreateModel(
            name='PartOf1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.offer')),
                ('ORID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.users'),
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.offer')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.product')),
            ],
        ),
        migrations.CreateModel(
            name='HasT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TGID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.tags')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.topping')),
            ],
        ),
        migrations.CreateModel(
            name='HasP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.product')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.topping')),
            ],
        ),
    ]
