# Generated by Django 4.2 on 2023-05-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_foodgroup_topping_foodgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='foodgroup',
            new_name='FID',
        ),
    ]
